In [1]:
#Chapter 1: Image Processing
# import libraries
import cv2 as cv
import numpy as np

img = cv.imread('stamp.png')

cv.imshow('Original', img)
cv.waitKey(0)   
cv.destroyAllWindows()

### Change The Size of Image

In [2]:
#Chapter 2: Image Transformation
# Reading a image and change the size
img = cv.imread('stamp.png')
img = cv.resize(img, (400, 400))
cv.imshow('Resized', img)
cv.waitKey(0) 

-1

In [3]:
#Chapter 3: Image Transformation
# Converting an image to grayscale
img = cv.imread('stamp.png')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
cv.imshow('Gray', gray)
cv.waitKey(0)

-1

In [5]:
# Chapter 4: Image Transformation
# Convert image into black and white
img = cv.imread('stamp.png')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
ret, thresh = cv.threshold(gray, 127, 255, cv.THRESH_BINARY)
(thresh, binary) = cv.threshold(gray, 127, 255, cv.THRESH_BINARY)
cv.imshow('original', img)
cv.imshow('gray', gray)
cv.imshow('black and white', binary)
cv.imshow('Threshold', thresh)
cv.waitKey(0)
cv.destroyAllWindows()

In [6]:
# Chapter 5: Save Image
# Save image
from cv2 import imwrite
from cv2 import imread
img = cv.imread('stamp.png')
gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
#ret, thresh = cv.threshold(gray, 127, 255, cv.THRESH_BINARY)
(thresh, binary) = cv.threshold(gray, 127, 255, cv.THRESH_BINARY)
imwrite('stamp_gray.png', gray)
imwrite('stamp_binary.png', binary)



True

In [1]:
# Chapter 6: Video Writing
import cv2 as cv

cap = cv.VideoCapture('promo.mov')

# indicate the number of frames to skip
if (cap.isOpened() == False): 
  print("Error opening video stream or file")
# Read until video is completed
while (cap.isOpened()):
    ret, frame = cap.read()
    if ret == True:
        cv.imshow('Frame', frame)
        if cv.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break    

cap.release()
cv.destroyAllWindows()


In [1]:
# Chapter 7: Video Writing
# Convert video to grayscale
import cv2 as cv

cap = cv.VideoCapture('promo.mov')
while (True):
  (ret,frame)= cap.read()
  grayframe = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
  (thresh, binary) = cv.threshold(grayframe, 127, 255, cv.THRESH_BINARY)
  # to Show the Video
  if ret == True:
        cv.imshow('Frame',   binary)
        # To Quit key with Q
        if cv.waitKey(1) & 0xFF == ord('q'):
            break
  else:
        break  
cap.release()
cv.destroyAllWindows()

In [1]:
# Chapter 8: Video Writing
import cv2 as cv
cap = cv.VideoCapture('promo.mov')
# Writing Formet, codec, video writer object and file output
out = cv.VideoWriter('outputnew.avi', cv.VideoWriter_fourcc('M','J','P','G'), 30, (640,480),isColor=False)
while (True):
  (ret,frame)= cap.read()
  grayframe = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
  #(thresh, binary) = cv.threshold(grayframe, 127, 255, cv.THRESH_BINARY)
  # to Show the Video
  if ret == True:
        out.write(grayframe)
        cv.imshow('Frame',   grayframe)
        # To Quit key with Q
        if cv.waitKey(1) & 0xFF == ord('q'):
            break
  else:
        break  
cap.release()
out.release()
cv.destroyAllWindows()


In [4]:
# Chapter 9: how to capture video from webcam
import cv2 as cv
import numpy as np
cap = cv.VideoCapture(0) # 0 is the id of the webcam
# Read until video is completed
while (cap.isOpened()):
    # Capture frame-by-frame
    ret, frame = cap.read()
    if ret == True:
        # Display the resulting frame
        cv.imshow('Frame', frame)
        if cv.waitKey(1) & 0xFF == ord('q'):
            break
    else:
        break
# Step 5: Release the VideoCapture object
cap.release()
cv.destroyAllWindows()


In [2]:
# Chapter 10: Show the Capture from video
import cv2 as cv
import numpy as np
cap = cv.VideoCapture(0) # 0 is the id of the webcam
# Read until video is completed
while (True):
    # Capture frame-by-frame
    (ret, frame) = cap.read()
    # Convert the Color image to Gray image
    cv.imshow('Orginal', frame)
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    cv.imshow('Gray', gray)
    # Display the resulting frame
    if cv.waitKey(1) & 0xFF == ord('q'):
        break

cap.release()
cv.destroyAllWindows()


In [2]:
# Chapter 11: Change the Brightness of the image
import cv2 as cv
import numpy as np
cap = cv.VideoCapture(0) # 0 is the id of the webcam
# Read until video is completed
while (True):
    # Capture frame-by-frame
    (ret, frame) = cap.read()
    # Convert the Color image to Gray image
    cv.imshow('Orginal', frame)
    gray = cv.cvtColor(frame, cv.COLOR_BGR2GRAY)
    cv.imshow('Gray', gray)
    # Display the resulting frame
    if cv.waitKey(1) & 0xFF == ord('q'):
        break
cap.release()
cv.destroyAllWindows()


In [36]:
# Chapter 11: No WebCam
# Chapter 12: No WebCam
# Chapter 13: Basic manipulation of images
import cv2 as cv
import numpy as np
img = cv.imread('stamp.png')

# Resize the image to 50% of the original size
resized_img = cv.resize(img, (450,250), fx=0.5, fy=0.5)
# # Convert the image to grayscale
gray_img = cv.cvtColor(resized_img, cv.COLOR_BGR2GRAY)

# # blur the image
blur_img = cv.GaussianBlur(gray_img, (23,23), 0)

# Edge detection
edges = cv.Canny(blur_img, 48, 48)
# Thickness of Lines
mat_kernal = np.ones((5,5), np.uint8)
dilated_img = cv.dilate(edges, (mat_kernal), iterations=2)

# Thinner outlines
oro_img = cv.erode(dilated_img, (mat_kernal), iterations=2)

# Crop the image using numPy indexing
print("Image Shape: ", img.shape)
crop_img = img[0:250, 0:450]





cv.imshow('original', img)
cv.imshow('resized', resized_img)
cv.imshow('gray', gray_img)
cv.imshow('blur', blur_img)
cv.imshow('edges', edges)
cv.imshow('dilated', dilated_img)
cv.imshow('thick', oro_img)
cv.imshow('crop', crop_img)
cv.waitKey(0)
cv.destroyAllWindows()

Image Shape:  (500, 500, 3)


In [40]:
# Chapter 14: How to draw a lines and shapes in python
import cv2 as cv
import numpy as np

# Deaw a canvas
canvas = np.zeros((300,300))
#img = np.ones((300,300))
# Print the size of canvas
print("Print the Size of Canvas",canvas.shape)
# Adding Color to the canvas
img1 = np.zeros((600,600,3), np.uint8) # color channel
img1[:] = (255,0,0) # white color
# add trinagle in the canvas
img1[0:300, 0:300] = (0,0,255) # blue color

# adding lines
cv.line(img1, (0,0), (300,300), (255,255,255), 3)

# adding rectangle
cv.rectangle(img1, (50,100), (300,300), (0,255,0), 3)
# filled rectangle
cv.rectangle(img1, (50,100), (300,300), (0,255,0), -1)
# adding circle
cv.circle(img1, (150,150), 50, (0,0,255), 3)
# filled Circle
cv.circle(img1, (150,150), 50, (145,0,255), -1)
# adding text
cv.putText(img1, 'Zeeshan Work on OpenCV', (10,500), cv.FONT_HERSHEY_SIMPLEX, 1, (255,255,255), 2)



# print(canvas)
#cv.imshow('black', canvas)
#cv.imshow('white', img)
cv.imshow('colored', img1)

cv.waitKey(0)
cv.destroyAllWindows()

Print the Size of Canvas (300, 300)


[histogram equalization opencv](https://docs.opencv.org/3.4/d4/d1b/tutorial_histogram_equalization.html)
#### Chapter 15 and 16 For WebCam


In [6]:
# Chapter 17 : How to join two images
import cv2 as cv
import numpy as np

img = cv.imread('stamp.png')
# Stacking same images
img1 = np.hstack((img, img))

# Vertical stacking
img2 = np.vstack((img, img))

# you can only stack images of same size
#   img3 = np.vstack((img, img1))

#cv.imshow('horizontal', img1)
cv.imshow('vertical', img2)

cv.waitKey(0)
cv.destroyAllWindows()



### Change The perceptive of Image

In [12]:
import numpy as np
import cv2

# read input
img = cv2.imread("wrap.jpg")

# specify desired output size 
width = 350
height = 350

# specify conjugate x,y coordinates (not y,x)
input = np.float32([[62,71], [418,59], [442,443], [29,438]])
output = np.float32([[0,0], [width-1,0], [width-1,height-1], [0,height-1]])

# compute perspective matrix
matrix = cv2.getPerspectiveTransform(input,output)

print(matrix.shape)
print(matrix)

# do perspective transformation setting area outside input to black
imgOutput = cv2.warpPerspective(img, matrix, (width,height), cv2.INTER_LINEAR, borderMode=cv2.BORDER_CONSTANT, borderValue=(0,0,0))
print(imgOutput.shape)

# save the warped output
cv2.imwrite("sudoku_warped.jpg", imgOutput)

# show the result
cv2.imshow("result", imgOutput)
cv2.waitKey(0)
cv2.destroyAllWindows()

(3, 3)
[[ 1.06962126e+00  9.61784781e-02 -7.31451899e+01]
 [ 3.87381282e-02  1.14923114e+00 -8.39971746e+01]
 [ 1.45318012e-04  4.58051741e-04  1.00000000e+00]]
(350, 350, 3)
